/* Generated by bin2c, do not edit manually */
#ifndef ___khz_h_included
#define ___khz_h_included

/* Contents of file 1khz.wav */
extern const long int _khz_wav_size;
extern const unsigned char _khz_wav[264646];

#endif    /* ___khz_h_included */
